export class Country {
  constructor(init: Country) {
    Object.assign(this, init)
  }
  id: number
  name: string
  twoLetter: string
}

// DBと値を合わせる
// DBから取得した値を使う手もあるが変更が少ないため、
// 画面からのAPIコールを減らすために定数として定義することとした
const values = [
  { id: 1, twoLetter: 'AD', name: 'Andorra' },
  { id: 2, twoLetter: 'AE', name: 'United Arab Emirates' },
  { id: 3, twoLetter: 'AF', name: 'Afghanistan' },
  { id: 4, twoLetter: 'AG', name: 'Antigua and Barbuda' },
  { id: 5, twoLetter: 'AI', name: 'Anguilla' },
  { id: 6, twoLetter: 'AL', name: 'Albania' },
  { id: 7, twoLetter: 'AM', name: 'Armenia' },
  { id: 8, twoLetter: 'AO', name: 'Angola' },
  { id: 9, twoLetter: 'AQ', name: 'Antarctica' },
  { id: 10, twoLetter: 'AR', name: 'Argentina' },
  { id: 11, twoLetter: 'AS', name: 'American Samoa' },
  { id: 12, twoLetter: 'AT', name: 'Austria' },
  { id: 13, twoLetter: 'AU', name: 'Australia' },
  { id: 14, twoLetter: 'AW', name: 'Aruba' },
  { id: 15, twoLetter: 'AX', name: 'Åland Islands' },
  { id: 16, twoLetter: 'AZ', name: 'Azerbaijan' },
  { id: 17, twoLetter: 'BA', name: 'Bosnia and Herzegovina' },
  { id: 18, twoLetter: 'BB', name: 'Barbados' },
  { id: 19, twoLetter: 'BD', name: 'Bangladesh' },
  { id: 20, twoLetter: 'BE', name: 'Belgium' },
  { id: 21, twoLetter: 'BF', name: 'Burkina Faso' },
  { id: 22, twoLetter: 'BG', name: 'Bulgaria' },
  { id: 23, twoLetter: 'BH', name: 'Bahrain' },
  { id: 24, twoLetter: 'BI', name: 'Burundi' },
  { id: 25, twoLetter: 'BJ', name: 'Benin' },
  { id: 26, twoLetter: 'BL', name: 'Saint Barthélemy' },
  { id: 27, twoLetter: 'BM', name: 'Bermuda' },
  { id: 28, twoLetter: 'BN', name: 'Brunei Darussalam' },
  { id: 29, twoLetter: 'BO', name: 'Bolivia (Plurinational State of)' },
  { id: 30, twoLetter: 'BQ', name: 'Bonaire, Sint Eustatius and Saba' },
  { id: 31, twoLetter: 'BR', name: 'Brazil' },
  { id: 32, twoLetter: 'BS', name: 'Bahamas' },
  { id: 33, twoLetter: 'BT', name: 'Bhutan' },
  { id: 34, twoLetter: 'BV', name: 'Bouvet Island' },
  { id: 35, twoLetter: 'BW', name: 'Botswana' },
  { id: 36, twoLetter: 'BY', name: 'Belarus' },
  { id: 37, twoLetter: 'BZ', name: 'Belize' },
  { id: 38, twoLetter: 'CA', name: 'Canada' },
  { id: 39, twoLetter: 'CC', name: 'Cocos (Keeling) Islands' },
  { id: 40, twoLetter: 'CD', name: 'Congo, Democratic Republic of the' },
  { id: 41, twoLetter: 'CF', name: 'Central African Republic' },
  { id: 42, twoLetter: 'CG', name: 'Congo' },
  { id: 43, twoLetter: 'CH', name: 'Switzerland' },
  { id: 44, twoLetter: 'CI', name: "Côte d'Ivoire" },
  { id: 45, twoLetter: 'CK', name: 'Cook Islands' },
  { id: 46, twoLetter: 'CL', name: 'Chile' },
  { id: 47, twoLetter: 'CM', name: 'Cameroon' },
  { id: 48, twoLetter: 'CN', name: 'China' },
  { id: 49, twoLetter: 'CO', name: 'Colombia' },
  { id: 50, twoLetter: 'CR', name: 'Costa Rica' },
  { id: 51, twoLetter: 'CU', name: 'Cuba' },
  { id: 52, twoLetter: 'CV', name: 'Cabo Verde' },
  { id: 53, twoLetter: 'CW', name: 'Curaçao' },
  { id: 54, twoLetter: 'CX', name: 'Christmas Island' },
  { id: 55, twoLetter: 'CY', name: 'Cyprus' },
  { id: 56, twoLetter: 'CZ', name: 'Czechia' },
  { id: 57, twoLetter: 'DE', name: 'Germany' },
  { id: 58, twoLetter: 'DJ', name: 'Djibouti' },
  { id: 59, twoLetter: 'DK', name: 'Denmark' },
  { id: 60, twoLetter: 'DM', name: 'Dominica' },
  { id: 61, twoLetter: 'DO', name: 'Dominican Republic' },
  { id: 62, twoLetter: 'DZ', name: 'Algeria' },
  { id: 63, twoLetter: 'EC', name: 'Ecuador' },
  { id: 64, twoLetter: 'EE', name: 'Estonia' },
  { id: 65, twoLetter: 'EG', name: 'Egypt' },
  { id: 66, twoLetter: 'EH', name: 'Western Sahara' },
  { id: 67, twoLetter: 'ER', name: 'Eritrea' },
  { id: 68, twoLetter: 'ES', name: 'Spain' },
  { id: 69, twoLetter: 'ET', name: 'Ethiopia' },
  { id: 70, twoLetter: 'FI', name: 'Finland' },
  { id: 71, twoLetter: 'FJ', name: 'Fiji' },
  { id: 72, twoLetter: 'FK', name: 'Falkland Islands (Malvinas)' },
  { id: 73, twoLetter: 'FM', name: 'Micronesia (Federated States of)' },
  { id: 74, twoLetter: 'FO', name: 'Faroe Islands' },
  { id: 75, twoLetter: 'FR', name: 'France' },
  { id: 76, twoLetter: 'GA', name: 'Gabon' },
  { id: 77, twoLetter: 'GB', name: 'United Kingdom of Great Britain and Northern Ireland' },
  { id: 78, twoLetter: 'GD', name: 'Grenada' },
  { id: 79, twoLetter: 'GE', name: 'Georgia' },
  { id: 80, twoLetter: 'GF', name: 'French Guiana' },
  { id: 81, twoLetter: 'GG', name: 'Guernsey' },
  { id: 82, twoLetter: 'GH', name: 'Ghana' },
  { id: 83, twoLetter: 'GI', name: 'Gibraltar' },
  { id: 84, twoLetter: 'GL', name: 'Greenland' },
  { id: 85, twoLetter: 'GM', name: 'Gambia' },
  { id: 86, twoLetter: 'GN', name: 'Guinea' },
  { id: 87, twoLetter: 'GP', name: 'Guadeloupe' },
  { id: 88, twoLetter: 'GQ', name: 'Equatorial Guinea' },
  { id: 89, twoLetter: 'GR', name: 'Greece' },
  { id: 90, twoLetter: 'GS', name: 'South Georgia and the South Sandwich Islands' },
  { id: 91, twoLetter: 'GT', name: 'Guatemala' },
  { id: 92, twoLetter: 'GU', name: 'Guam' },
  { id: 93, twoLetter: 'GW', name: 'Guinea-Bissau' },
  { id: 94, twoLetter: 'GY', name: 'Guyana' },
  { id: 95, twoLetter: 'HK', name: 'Hong Kong' },
  { id: 96, twoLetter: 'HM', name: 'Heard Island and McDonald Islands' },
  { id: 97, twoLetter: 'HN', name: 'Honduras' },
  { id: 98, twoLetter: 'HR', name: 'Croatia' },
  { id: 99, twoLetter: 'HT', name: 'Haiti' },
  { id: 100, twoLetter: 'HU', name: 'Hungary' },
  { id: 101, twoLetter: 'ID', name: 'Indonesia' },
  { id: 102, twoLetter: 'IE', name: 'Ireland' },
  { id: 103, twoLetter: 'IL', name: 'Israel' },
  { id: 104, twoLetter: 'IM', name: 'Isle of Man' },
  { id: 105, twoLetter: 'IN', name: 'India' },
  { id: 106, twoLetter: 'IO', name: 'British Indian Ocean Territory' },
  { id: 107, twoLetter: 'IQ', name: 'Iraq' },
  { id: 108, twoLetter: 'IR', name: 'Iran (Islamic Republic of)' },
  { id: 109, twoLetter: 'IS', name: 'Iceland' },
  { id: 110, twoLetter: 'IT', name: 'Italy' },
  { id: 111, twoLetter: 'JE', name: 'Jersey' },
  { id: 112, twoLetter: 'JM', name: 'Jamaica' },
  { id: 113, twoLetter: 'JO', name: 'Jordan' },
  { id: 114, twoLetter: 'JP', name: 'Japan' },
  { id: 115, twoLetter: 'KE', name: 'Kenya' },
  { id: 116, twoLetter: 'KG', name: 'Kyrgyzstan' },
  { id: 117, twoLetter: 'KH', name: 'Cambodia' },
  { id: 118, twoLetter: 'KI', name: 'Kiribati' },
  { id: 119, twoLetter: 'KM', name: 'Comoros' },
  { id: 120, twoLetter: 'KN', name: 'Saint Kitts and Nevis' },
  { id: 121, twoLetter: 'KP', name: "Korea (Democratic People's Republic of)" },
  { id: 122, twoLetter: 'KR', name: 'Korea, Republic of' },
  { id: 123, twoLetter: 'KW', name: 'Kuwait' },
  { id: 124, twoLetter: 'KY', name: 'Cayman Islands' },
  { id: 125, twoLetter: 'KZ', name: 'Kazakhstan' },
  { id: 126, twoLetter: 'LA', name: "Lao People's Democratic Republic" },
  { id: 127, twoLetter: 'LB', name: 'Lebanon' },
  { id: 128, twoLetter: 'LC', name: 'Saint Lucia' },
  { id: 129, twoLetter: 'LI', name: 'Liechtenstein' },
  { id: 130, twoLetter: 'LK', name: 'Sri Lanka' },
  { id: 131, twoLetter: 'LR', name: 'Liberia' },
  { id: 132, twoLetter: 'LS', name: 'Lesotho' },
  { id: 133, twoLetter: 'LT', name: 'Lithuania' },
  { id: 134, twoLetter: 'LU', name: 'Luxembourg' },
  { id: 135, twoLetter: 'LV', name: 'Latvia' },
  { id: 136, twoLetter: 'LY', name: 'Libya' },
  { id: 137, twoLetter: 'MA', name: 'Morocco' },
  { id: 138, twoLetter: 'MC', name: 'Monaco' },
  { id: 139, twoLetter: 'MD', name: 'Moldova, Republic of' },
  { id: 140, twoLetter: 'ME', name: 'Montenegro' },
  { id: 141, twoLetter: 'MF', name: 'Saint Martin (French part)' },
  { id: 142, twoLetter: 'MG', name: 'Madagascar' },
  { id: 143, twoLetter: 'MH', name: 'Marshall Islands' },
  { id: 144, twoLetter: 'MK', name: 'North Macedonia' },
  { id: 145, twoLetter: 'ML', name: 'Mali' },
  { id: 146, twoLetter: 'MM', name: 'Myanmar' },
  { id: 147, twoLetter: 'MN', name: 'Mongolia' },
  { id: 148, twoLetter: 'MO', name: 'Macao' },
  { id: 149, twoLetter: 'MP', name: 'Northern Mariana Islands' },
  { id: 150, twoLetter: 'MQ', name: 'Martinique' },
  { id: 151, twoLetter: 'MR', name: 'Mauritania' },
  { id: 152, twoLetter: 'MS', name: 'Montserrat' },
  { id: 153, twoLetter: 'MT', name: 'Malta' },
  { id: 154, twoLetter: 'MU', name: 'Mauritius' },
  { id: 155, twoLetter: 'MV', name: 'Maldives' },
  { id: 156, twoLetter: 'MW', name: 'Malawi' },
  { id: 157, twoLetter: 'MX', name: 'Mexico' },
  { id: 158, twoLetter: 'MY', name: 'Malaysia' },
  { id: 159, twoLetter: 'MZ', name: 'Mozambique' },
  { id: 160, twoLetter: 'NA', name: 'Namibia' },
  { id: 161, twoLetter: 'NC', name: 'New Caledonia' },
  { id: 162, twoLetter: 'NE', name: 'Niger' },
  { id: 163, twoLetter: 'NF', name: 'Norfolk Island' },
  { id: 164, twoLetter: 'NG', name: 'Nigeria' },
  { id: 165, twoLetter: 'NI', name: 'Nicaragua' },
  { id: 166, twoLetter: 'NL', name: 'Netherlands' },
  { id: 167, twoLetter: 'NO', name: 'Norway' },
  { id: 168, twoLetter: 'NP', name: 'Nepal' },
  { id: 169, twoLetter: 'NR', name: 'Nauru' },
  { id: 170, twoLetter: 'NU', name: 'Niue' },
  { id: 171, twoLetter: 'NZ', name: 'New Zealand' },
  { id: 172, twoLetter: 'OM', name: 'Oman' },
  { id: 173, twoLetter: 'PA', name: 'Panama' },
  { id: 174, twoLetter: 'PE', name: 'Peru' },
  { id: 175, twoLetter: 'PF', name: 'French Polynesia' },
  { id: 176, twoLetter: 'PG', name: 'Papua New Guinea' },
  { id: 177, twoLetter: 'PH', name: 'Philippines' },
  { id: 178, twoLetter: 'PK', name: 'Pakistan' },
  { id: 179, twoLetter: 'PL', name: 'Poland' },
  { id: 180, twoLetter: 'PM', name: 'Saint Pierre and Miquelon' },
  { id: 181, twoLetter: 'PN', name: 'Pitcairn' },
  { id: 182, twoLetter: 'PR', name: 'Puerto Rico' },
  { id: 183, twoLetter: 'PS', name: 'Palestine, State of' },
  { id: 184, twoLetter: 'PT', name: 'Portugal' },
  { id: 185, twoLetter: 'PW', name: 'Palau' },
  { id: 186, twoLetter: 'PY', name: 'Paraguay' },
  { id: 187, twoLetter: 'QA', name: 'Qatar' },
  { id: 188, twoLetter: 'RE', name: 'Réunion' },
  { id: 189, twoLetter: 'RO', name: 'Romania' },
  { id: 190, twoLetter: 'RS', name: 'Serbia' },
  { id: 191, twoLetter: 'RU', name: 'Russian Federation' },
  { id: 192, twoLetter: 'RW', name: 'Rwanda' },
  { id: 193, twoLetter: 'SA', name: 'Saudi Arabia' },
  { id: 194, twoLetter: 'SB', name: 'Solomon Islands' },
  { id: 195, twoLetter: 'SC', name: 'Seychelles' },
  { id: 196, twoLetter: 'SD', name: 'Sudan' },
  { id: 197, twoLetter: 'SE', name: 'Sweden' },
  { id: 198, twoLetter: 'SG', name: 'Singapore' },
  { id: 199, twoLetter: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha' },
  { id: 200, twoLetter: 'SI', name: 'Slovenia' },
  { id: 201, twoLetter: 'SJ', name: 'Svalbard and Jan Mayen' },
  { id: 202, twoLetter: 'SK', name: 'Slovakia' },
  { id: 203, twoLetter: 'SL', name: 'Sierra Leone' },
  { id: 204, twoLetter: 'SM', name: 'San Marino' },
  { id: 205, twoLetter: 'SN', name: 'Senegal' },
  { id: 206, twoLetter: 'SO', name: 'Somalia' },
  { id: 207, twoLetter: 'SR', name: 'Suriname' },
  { id: 208, twoLetter: 'SS', name: 'South Sudan' },
  { id: 209, twoLetter: 'ST', name: 'Sao Tome and Principe' },
  { id: 210, twoLetter: 'SV', name: 'El Salvador' },
  { id: 211, twoLetter: 'SX', name: 'Sint Maarten (Dutch part)' },
  { id: 212, twoLetter: 'SY', name: 'Syrian Arab Republic' },
  { id: 213, twoLetter: 'SZ', name: 'Eswatini' },
  { id: 214, twoLetter: 'TC', name: 'Turks and Caicos Islands' },
  { id: 215, twoLetter: 'TD', name: 'Chad' },
  { id: 216, twoLetter: 'TF', name: 'French Southern Territories' },
  { id: 217, twoLetter: 'TG', name: 'Togo' },
  { id: 218, twoLetter: 'TH', name: 'Thailand' },
  { id: 219, twoLetter: 'TJ', name: 'Tajikistan' },
  { id: 220, twoLetter: 'TK', name: 'Tokelau' },
  { id: 221, twoLetter: 'TL', name: 'Timor-Leste' },
  { id: 222, twoLetter: 'TM', name: 'Turkmenistan' },
  { id: 223, twoLetter: 'TN', name: 'Tunisia' },
  { id: 224, twoLetter: 'TO', name: 'Tonga' },
  { id: 225, twoLetter: 'TR', name: 'Turkey' },
  { id: 226, twoLetter: 'TT', name: 'Trinidad and Tobago' },
  { id: 227, twoLetter: 'TV', name: 'Tuvalu' },
  { id: 228, twoLetter: 'TW', name: 'Taiwan, Province of China' },
  { id: 229, twoLetter: 'TZ', name: 'Tanzania, United Republic of' },
  { id: 230, twoLetter: 'UA', name: 'Ukraine' },
  { id: 231, twoLetter: 'UG', name: 'Uganda' },
  { id: 232, twoLetter: 'UM', name: 'United States Minor Outlying Islands' },
  { id: 233, twoLetter: 'US', name: 'United States of America' },
  { id: 234, twoLetter: 'UY', name: 'Uruguay' },
  { id: 235, twoLetter: 'UZ', name: 'Uzbekistan' },
  { id: 236, twoLetter: 'VA', name: 'Holy See' },
  { id: 237, twoLetter: 'VC', name: 'Saint Vincent and the Grenadines' },
  { id: 238, twoLetter: 'VE', name: 'Venezuela (Bolivarian Republic of)' },
  { id: 239, twoLetter: 'VG', name: 'Virgin Islands (British)' },
  { id: 240, twoLetter: 'VI', name: 'Virgin Islands (U.S.)' },
  { id: 241, twoLetter: 'VN', name: 'Viet Nam' },
  { id: 242, twoLetter: 'VU', name: 'Vanuatu' },
  { id: 243, twoLetter: 'WF', name: 'Wallis and Futuna' },
  { id: 244, twoLetter: 'WS', name: 'Samoa' },
  { id: 245, twoLetter: 'YE', name: 'Yemen' },
  { id: 246, twoLetter: 'YT', name: 'Mayotte' },
  { id: 247, twoLetter: 'ZA', name: 'South Africa' },
  { id: 248, twoLetter: 'ZM', name: 'Zambia' },
  { id: 249, twoLetter: 'ZW', name: 'Zimbabwe' }
]

export const countries = values.map((value) => new Country(value))
