version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: stay_count_db
    restart: always
    environment:
      MYSQL_DATABASE: sc
      MYSQL_USER: sc
      MYSQL_PASSWORD: passwordA1!
      MYSQL_ROOT_PASSWORD: passwordA1!
    ports:
      - '33306:3306'
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
